obj-m := nrfble.o
nrfble-objs := nrf_ble.rust.o

CARGO ?= cargo +nightly

export c_flags

$(src)/target/x86_64-linux-kernel/debug/libnrf_ble.a: cargo_will_determine_dependencies
	cd $(src); $(CARGO) build -Z build-std=core,alloc --target=x86_64-linux-kernel

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/x86_64-linux-kernel/debug/lib%.a
	$(LD) -r -o $@ --whole-archive $<
